### ISSUE TITLE
May I ask you why did you clean up W-GAN model?

### ISSUE THREAD

**Issue by HudsonHuang** [JeremyCCHsu/vae-npvc#1]
I see there's wgan model in earlier commit, but now cleaned, how may I reproduce your result?

**Comment by JeremyCCHsu** [comment]
Thanks for reminding me. Sorry about my project management. The deleted codes belonged to my side project and were not used in the VAE or the VAWGAN project (the latter used WGAN with weight clipping). I'll update this repo with the VAWGAN code in December.

**Comment by HudsonHuang** [comment]
Thank you~best wishes.
