### ISSUE TITLE
How to convert nchw ops to nhwc ops?

### ISSUE THREAD

**Issue by poor1017** [JeremyCCHsu/vae-npvc#15]
Hi @JeremyCCHsu 

    Could you guide me on this convertion? I have no idea which ops are nchw, and which are nhwc.

Thank you.

**Comment by JeremyCCHsu** [comment]
It's just how you arrange the dimensions. See `nchw_to_nhwc` in `util/image.py` for the conversion.

**Comment by poor1017** [comment]
Thank you for your reply.
All I need to do is rearranging the dimensions, and change 'channels_first' in 'tf.layers.conv2d_transpose' to 'channels_last', right?

**Comment by poor1017** [comment]
There are two places need to treat: encoder and generator. Do nchw_to_nhwc, then do conv2d, then do nhwc_to_nchw. That's all.
