### ISSUE TITLE
dataset download link seems not working

### ISSUE THREAD

**Issue by triwoods** [JeremyCCHsu/vae-npvc#2]
here is the message I've got.

--2017-12-14 11:32:50--  http://datashare.is.ed.ac.uk/download/10283/2042/SUPERS                                         EDED_-_The_Voice_Conversion_Challenge_2016.zip
Resolving datashare.is.ed.ac.uk (datashare.is.ed.ac.uk)... 129.215.41.53
Connecting to datashare.is.ed.ac.uk (datashare.is.ed.ac.uk)|129.215.41.53|:80...                                          connected.
HTTP request sent, awaiting response... 302 Found : Moved Temporarily
Location: https://datashare.is.ed.ac.uk/download/10283/2042/SUPERSEDED_-_The_Voi                                         ce_Conversion_Challenge_2016.zip [following]
--2017-12-14 11:32:52--  https://datashare.is.ed.ac.uk/download/10283/2042/SUPER                                         SEDED_-_The_Voice_Conversion_Challenge_2016.zip
Connecting to datashare.is.ed.ac.uk (datashare.is.ed.ac.uk)|129.215.41.53|:443..                                         . connected.
HTTP request sent, awaiting response... 404 Not Found
2017-12-14 11:32:52 ERROR 404: Not Found.

unzip:  cannot find or open SUPERSEDED_-_The_Voice_Conversion_Challenge_2016.zip                                         , SUPERSEDED_-_The_Voice_Conversion_Challenge_2016.zip.zip or SUPERSEDED_-_The_V                                         oice_Conversion_Challenge_2016.zip.ZIP.
unzip:  cannot find or open vcc2016_training.zip, vcc2016_training.zip.zip or vc                                         c2016_training.zip.ZIP.
mv: cannot stat ‘vcc2016_training’: No such file or directory
unzip:  cannot find or open evaluation_all.zip, evaluation_all.zip.zip or evalua                                         tion_all.zip.ZIP.
rm: cannot remove ‘evaluation_all.zip’: No such file or directory
rm: cannot remove ‘vcc2016_training.zip’: No such file or directory

**Comment by JeremyCCHsu** [comment]
The download link is updated.
If they change the link again in the future, please contact the dataset host:
https://datashare.is.ed.ac.uk/handle/10283/2042
