### ISSUE TITLE
Issue with NHWC format

### ISSUE THREAD

**Issue by savi429** [JeremyCCHsu/vae-npvc#3]
As you said my tensorflow is working on cpu , so I changed format='NHWC' still getting same error:Conv2DCustomBackpropInputOp only supports NHWC.
so kindly tell me in which file I need to change.

**Comment by JeremyCCHsu** [comment]
Hi, you might have to 
1. replace `channels_first` with `channels_last` 
2. replace `NCHW` with `NHWC`

for every occurrence in the repo.

**Comment by savi429** [comment]
Hi,

I am working on non-parallel voice conversion using VAWGAN. while I am
trying to train the model  I am facing one issue so can you please tell me
about how to fix that issue.
Below I attached issue screenshot.
