### ISSUE TITLE
How to use change model from VAE to VAWGAN?

### ISSUE THREAD

**Issue by nvadigauvce** [JeremyCCHsu/vae-npvc#4]
Hi, 

I am trying to do non-parallel voice conversion, with VAE option I am able to do voice conversion. But when I changed model to VAWGAN, it is giving below error.

 python main.py --model VAWGAN --trainer VAWGANTrainer --architecture architecture-vawgan-vcc2016.json

FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "main.py", line 40, in <module>
    MODEL = getattr(module, args.model)
AttributeError: module 'model.vae' has no attribute 'VAWGAN'

**Comment by JeremyCCHsu** [comment]
Please switch to the `vawgan` branch to use the VAWGAN model.

**Comment by nvadigauvce** [comment]
Thanks Jeremy.
